name: Coding Interview

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install -r requirements-lint.txt
    - name: Run static checks
      run: |
        black data_structures tests
        flake8 data_structures tests
        isort data_structures tests
        mypy data_structures tests

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install .
        pip install -r requirements-test.txt
    - name: Run tests
      run: |
        pytest tests